name: wallies
channels:
  - conda-forge
  - defaults
dependencies:
  - autopep8=2.0.1
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - libffi=3.4.2
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - mypy=1.0.1
  - mypy_extensions=1.0.0
  - ncurses=6.3
  - openssl=3.0.8
  - pip=23.0.1
  - psutil=5.9.4
  - pycodestyle=2.10.0
  - python=3.11.0
  - python_abi=3.11
  - readline=8.1.2
  - setuptools=67.4.0
  - tk=8.6.12
  - tomli=2.0.1
  - wheel=0.38.4
  - xz=5.2.6
  - pip:
      - anyio==3.6.2
      - appdirs==1.4.4
      - apscheduler==3.10.1
      - better-exceptions==0.3.3
      - boto3==1.26.93
      - botocore==1.29.93
      - certifi==2022.12.7
      - click==8.1.3
      - colorama==0.4.6
      - colorthief==0.2.1
      - corefile==0.1.2
      - corelog==0.0.8
      - dnspython==2.3.0
      - email-validator==1.3.1
      - faker==17.6.0
      - fastapi==0.92.0
      - filetype==1.2.0
      - fs==2.4.16
      - h11==0.14.0
      - httpcore==0.16.3
      - httptools==0.5.0
      - httpx==0.23.3
      - idna==3.4
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - jmespath==1.0.1
      - markdown-it-py==2.2.0
      - markupsafe==2.1.2
      - mdurl==0.1.2
      - numpy==1.24.2
      - orjson==3.8.7
      - peewee==3.16.0
      - pillow==9.4.0
      - psycopg2==2.9.5
      - pydantic==1.10.5
      - pygments==2.14.0
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - python-multipart==0.0.6
      - pytz==2022.7.1
      - pytz-deprecation-shim==0.1.0.post0
      - pyyaml==6.0
      - rfc3986==1.5.0
      - rich==13.3.1
      - s3transfer==0.6.0
      - semver==2.13.0
      - six==1.16.0
      - sniffio==1.3.0
      - starlette==0.25.0
      - stringcase==1.2.0
      - structlog==22.3.0
      - typing-extensions==4.5.0
      - tzdata==2022.7
      - tzlocal==4.2
      - ujson==5.7.0
      - urllib3==1.26.15
      - uvicorn==0.20.0
      - uvloop==0.17.0
      - watchfiles==0.18.1
      - websockets==10.4
prefix: /Volumes/Devo/miniforge3/envs/wallies
