name: wallies
channels:
  - conda-forge
dependencies:
  - autopep8=2.0.1
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - libffi=3.4.2
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - mypy=1.0.1
  - mypy_extensions=1.0.0
  - ncurses=6.3
  - openssl=3.0.8
  - pip=23.0.1
  - psutil=5.9.4
  - pycodestyle=2.10.0
  - python=3.11.0
  - python_abi=3.11
  - readline=8.1.2
  - setuptools=67.4.0
  - tk=8.6.12
  - tomli=2.0.1
  - typing_extensions=4.7.0
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.2.6
  - pip:
      - anyio==3.7.0
      - appdirs==1.4.4
      - apscheduler==3.10.1
      - better-exceptions==0.3.3
      - boto3==1.26.165
      - botocore==1.29.165
      - certifi==2023.5.7
      - click==8.1.3
      - colorama==0.4.6
      - colorthief==0.2.1
      - corefile==0.1.2
      - corelog==0.0.9
      - corestring==0.1.19
      - faker==18.11.2
      - fastapi==0.99.0
      - filetype==1.2.0
      - fs==2.4.16
      - h11==0.14.0
      - httpcore==0.17.2
      - httpx==0.24.1
      - idna==3.4
      - jmespath==1.0.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - numpy==1.25.0
      - peewee==3.16.2
      - pillow==10.0.0
      - psycopg2-binary==2.9.6
      - pydantic==1.10.10
      - pygments==2.15.1
      - python-dateutil==2.8.2
      - pytz==2023.3
      - rich==13.4.2
      - s3transfer==0.6.1
      - semver==3.0.1
      - six==1.16.0
      - sniffio==1.3.0
      - starlette==0.27.0
      - stringcase==1.2.0
      - structlog==23.1.0
      - tabulate==0.9.0
      - types-tabulate==0.9.0.2
      - types-ujson==5.8.0.0
      - tzlocal==5.0.1
      - urllib3==1.26.16
      - uvicorn==0.22.0
prefix: /Volumes/Devo/Users/jago/miniforge3/envs/wallies
